## __Cuestión 1__

Crea dos vectores de igual longitud con valores entre 1 y 50 que sigan una distribución uniforme. 
Calcula:

La suma de sus elementos correspondientes (vector resultante)

El producto escalar de los dos vectores

La correlación entre ambos vectores

In [0]:
# Importamos la librería numpy para manejar operaciones vectoriales
import numpy as np

# Definimos la longitud de nuestros vectores.n = 10 como ejemplo.
n = 10

# Generamos el primer vector con valores enteros entre 1 y 50.
# Utilizamos np.random.randint que genera números aleatorios en el rango [1, 51) (el 51 es exclusivo).
v1 = np.random.randint(1, 51, size=n)

# Generamos el segundo vector de la misma manera.
v2 = np.random.randint(1, 51, size=n)

# Calculamos la suma de ambos vectores, sumando elemento a elemento.
suma_vectores = v1 + v2

# Calculamos el producto escalar (dot product) multiplicando cada par de elementos correspondientes y sumando los resultados.
producto_escalar = np.dot(v1, v2)

# Calculamos la correlación entre ambos vectores.
# Usamos np.corrcoef que devuelve la matriz de correlación y extraemos el coeficiente en la posición [0, 1].
correlacion = np.corrcoef(v1, v2)[0, 1]

# Imprimimos los resultados para ver la salida.
print("Vector 1:")
print(v1)
print("Vector 2:")
print(v2)
print("Suma de vectores:")
print(suma_vectores)
print("Producto escalar:")
print(producto_escalar)
print("Correlación entre los vectores:")
print(correlacion)



Vector 1:
[42 28 16 15 47 44  3 37  7 21]
Vector 2:
[ 9 39 18  4 25 14 50  9 26  2]
Suma de vectores:
[51 67 34 19 72 58 53 46 33 23]
Producto escalar:
4316
Correlación entre los vectores:
-0.34951804793171165


## Cuestión 2

Defina una función que encuentre la intersección de dos listas; es decir, que devuelva sus elementos comunes

In [0]:
def listInt(l1, l2):
    # Comprobamos que ambas entradas sean listas. Si no lo son, lanzamos un error.
    if not isinstance(l1, list) or not isinstance(l2, list):
        raise ValueError("Debes introducir listas")
    
    # Calculamos la intersección
    # Convertimos cada elemento a cadena
    resultado = []
    for item in l1:
        if item in l2 and str(item) not in resultado:
            resultado.append(str(item))
    # Devolvemos la lista con los elementos comunes ya convertidos a string.
    return resultado

# Ejemplo de prueba:
lA = [1, 7, 9, "o", "p"]
lB = [0, 1, 9, "p", "z"]

res = listInt(lA, lB)
print("Los elementos comunes entre lA y lB son:")
print(res)


Los elementos comunes entre lA y lB son:
['1', '9', 'p']


## Cuestión 3

Defina una función que filtre palabras de una lista según su longitud. La función debe tomar una lista de palabras y un número entero, y devolver una lista con las palabras cuya longitud sea mayor o igual al número dado

In [0]:
def fwords(wordList, minLen):
    # Verificamos que la entrada sea una lista.
    if not isinstance(wordList, list):
        raise ValueError("Debes introducir una lista")
    
    # Verificamos que minLen sea un número entero.
    if not isinstance(minLen, int):
        raise ValueError("Debes introducir un número entero")
    
    # Convertimos la lista a un vector de cadenas.
    words = [str(word) for word in wordList]
    
    # Filtramos las palabras cuya longitud es mayor o igual a minLen.
    filt = [word for word in words if len(word) >= minLen]
    
    # Devolvemos el resultado como una lista, cumpliendo con el enunciado.
    return filt

# Ejemplo de prueba:
wList = ["Perro", "Columpio", "Y", "Programación", "Data", "Caballo"]
# Llamamos a la función para filtrar las palabras con longitud >= 4.
res = fwords(wList, 4)

# Imprimimos el resultado para visualizar las palabras filtradas.
print("Palabras con longitud mayor o igual a 4:")
print(res)


Palabras con longitud mayor o igual a 4:
['Perro', 'Columpio', 'Programación', 'Data', 'Caballo']


## Cuestión 5

Defina una función que reciba una palabra y cuente el número de vocales que tiene dicha palabra

In [0]:
def count_vowels(word):
    # Verificamos que la entrada sea un string.
    if not isinstance(word, str):
        raise ValueError("La entrada debe ser una palabra")
    
    # Verificamos que el string no esté vacío.
    if len(word) == 0:
        raise ValueError("La entrada debe ser una palabra")
    
    # Convertimos la palabra a minúsculas para facilitar la comparación.
    word_lower = word.lower()
    
    # Definimos las vocales (incluyendo las acentuadas).
    vowels = set("aeiouáéíóú")
    
    # Contamos las vocales en la palabra.
    count = sum(1 for char in word_lower if char in vowels)
    
    return count

# Ejemplo de prueba:
palabra = "Programación"
vowel_count = count_vowels(palabra)
print(f"La palabra '{palabra}' tiene {vowel_count} vocales.")


La palabra 'Programación' tiene 5 vocales.


## APLICACIÓN DE LOS TEST UNITARIOS

### Test unitarios de la función listInt de la CUESTIÓN 2


In [0]:
pip install pytest

  Obtaining dependency information for pytest from https://files.pythonhosted.org/packages/30/3d/64ad57c803f1fa1e963a7946b6e0fea4a70df53c1a7fed304586539c2bac/pytest-8.3.5-py3-none-any.whl.metadata
  Obtaining dependency information for iniconfig from https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for pluggy<2,>=1.5 from https://files.pythonhosted.org/packages/88/5f/e351af9a41f866ac3f1fac4ca0613908d9a41741cfcf2228f4ad853b697d/pluggy-1.5.0-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/343.6 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━ 204.8/343.6 kB 6.0 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.6/343.6 kB 6.1 MB/s eta 0:00:00
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.


In [0]:
%restart_python

In [0]:
import pytest

def listInt(l1, l2):
    # Comprobamos que ambas entradas sean listas. Si no lo son, lanzamos un error.
    if not isinstance(l1, list) or not isinstance(l2, list):
        raise ValueError("Debes introducir listas")
    
    # Calculamos la intersección, recorriendo l1 y comprobando si cada elemento está en l2.
    # Convertimos cada elemento a string para imitar el comportamiento de as.character() de R.
    resultado = []
    for item in l1:
        if item in l2 and str(item) not in resultado:
            resultado.append(str(item))
    return resultado

# Test unitarios para la función listInt

def test_listInt_invalid_first_arg():
    # Cuando la primera entrada no es una lista.
    with pytest.raises(ValueError, match="Debes introducir listas"):
        listInt(1, [1, 2, 3])

def test_listInt_invalid_second_arg():
    # Cuando la segunda entrada no es una lista.
    with pytest.raises(ValueError, match="Debes introducir listas"):
        listInt([1, 2, 3], 1)

def test_listInt_correct_intersection():
    # Probamos que la función retorna la intersección correcta.
    lA = [1, 2, 5, "a", "b"]
    lB = [2, 3, 5, "a", "c"]
    # Se espera que, tras la conversión a string, la intersección sea: "2", "5" y "a".
    result = listInt(lA, lB)
    expected = ["2", "5", "a"]
    assert result == expected

def test_listInt_empty_intersection():
    # Probamos que si no hay intersección se retorne una lista vacía.
    lA = [1, 2, 3]
    lB = [4, 5, 6]
    result = listInt(lA, lB)
    expected = []
    assert result == expected



### Test unitarios de la función count_vowels de la CUESTIÓN 5

In [0]:
import pytest

# La función count_vowels que vamos a testear
def count_vowels(word):
    # Verificamos que la entrada sea un string.
    if not isinstance(word, str):
        raise ValueError("La entrada debe ser una palabra")
    
    # Verificamos que el string no esté vacío.
    if len(word) == 0:
        raise ValueError("La entrada debe ser una palabra")
    
    # Convertimos la palabra a minúsculas para facilitar la comparación.
    word_lower = word.lower()
    
    # Definimos las vocales (incluyendo las acentuadas).
    vowels = set("aeiouáéíóú")
    
    # Contamos las vocales en la palabra.
    count = sum(1 for char in word_lower if char in vowels)
    
    return count

# Test para entradas inválidas
def test_invalid_input():
    with pytest.raises(ValueError, match="La entrada debe ser una palabra"):
        count_vowels(123)
    with pytest.raises(ValueError, match="La entrada debe ser una palabra"):
        count_vowels(["hola", "mundo"])
    with pytest.raises(ValueError, match="La entrada debe ser una palabra"):
        count_vowels("")

# Test para verificar el conteo correcto de vocales
def test_count_vowels_correct():
    # 'hola' tiene 2 vocales: o, a
    assert count_vowels("hola") == 2

    # 'programacion' contiene: o, a, a, i, o → 5 vocales
    assert count_vowels("programacion") == 5

    # Comprobamos que la función sea insensible a mayúsculas
    assert count_vowels("AEIOU") == 5
    assert count_vowels("aeiou") == 5

# Test para el conteo de vocales en palabras con acento
def test_count_vowels_accented():
    # La palabra "programación" tiene 5 vocales: o, a, a, i, ó
    assert count_vowels("programación") == 5
